Models/Activity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Activity
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [DataType(DataType.Time)]
        public string Time { get; set; }

        public int ActivityTypeID { get; set; }
        public virtual ActivityType ActivityType { get; set; }

        public int ActivityStatusID { get; set; }
        public virtual ActivityStatus ActivityStatus { get; set; }

        public int PersonID { get; set; }
        public string PersonName { get; set; }

    }
}

Models/ActivityType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
    }
}

Models/Contribution.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public int ID { get; set; }
        public string GuestName { get; set; }
        public string Quantity { get; set; }
        public int EventId { get; set; }
        public int ContributionTypeID { get; set; }
    
        public virtual ContributionType ContributionType { get; set; }
    }
}

Models/ContributionType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionType
    {
        public ContributionType()
        {
            this.Contribution = new HashSet<Contribution>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Contribution> Contribution { get; set; }
    }
}

Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ActivityController : Controller
    {
        private MainDBContext db = new MainDBContext();

        //
        // GET: /Activity/

        public ActionResult Index()
        {


            if (Session["ID"]==null) { return RedirectToAction("Index", "Connection"); }
            else
            {
                if (Session["Admin"].ToString() != "Admin")
                {
                    int personid = int.Parse(Session["ID"].ToString());
                    var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus).Where(a => a.PersonID == personid);
                    ViewBag.name = Session["Name"];
                    return View(activity.ToList());
                }
                else {
                    var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus);

                    return View(activity.ToList());
                }
                
            }
        }

        //
        // GET: /Activity/Details/5

        public ActionResult Details(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // GET: /Activity/Create

        public ActionResult Create()
        {
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type");
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status");
            return View();
        }
        
        //
        // POST: /Activity/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Activity activity)
        {
            if (ModelState.IsValid)
            {

                int personid = int.Parse(Session["ID"].ToString());
                activity.PersonID = personid;
                activity.PersonName = Session["Name"].ToString();
                activity.ActivityStatusID = 3;
                db.Activity.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // GET: /Activity/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // POST: /Activity/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Activity activity)
        {
            if (ModelState.IsValid)
            {
                int personid = int.Parse(Session["ID"].ToString());
                activity.PersonID = personid;
                activity.ActivityStatusID = 3;
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // GET: /Activity/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activity.Find(id);
            db.Activity.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Connection");
        }

        public ActionResult Friend(string FriendName)
        {

            if (!string.IsNullOrEmpty(FriendName)) { return View(db.Person.Include(m => m.PersonRole).Where(m => m.Name.Contains(FriendName)).ToList()); }
            return View(db.Person.Include(m => m.PersonRole).ToList());
        }

        public ActionResult AddFriend()
        {

            return View();
        }

        public ActionResult Contribution(int id=0)
        {
            var contributionlist = db.Contribution.Where(c => c.EventId==id);
            return View(contributionlist.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ContributionController : Controller
    {
        private MainDBContext db = new MainDBContext();

        //
        // GET: /Contribution/

        public ActionResult Index()
        {
            var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus);
            
            return View(activity.ToList());
        }


        
        public ActionResult Viewall()
        {

            var contribution = db.Contribution.Include(c => c.ContributionType);
            return View(contribution.ToList());
        }

        //
        // GET: /Contribution/Details/5

        public ActionResult Details(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // GET: /Contribution/Create

        public ActionResult Create(int id = 0)
        {
            Session["EventID"] = id;
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type");
            return View();
        }

        //
        // POST: /Contribution/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                contribution.EventId = int.Parse(@Session["EventID"].ToString());
                db.Contribution.Add(contribution);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // POST: /Contribution/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contribution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // POST: /Contribution/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contribution contribution = db.Contribution.Find(id);
            db.Contribution.Remove(contribution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class PersonController : Controller
    {
        private MainDBContext db = new MainDBContext();


        

        //
        // GET: /Person/

        public ActionResult Index()
        {
            if ((Session["Admin"]==null) || (Session["Admin"]!=null) &&(Session["Admin"].ToString()!="Admin")) { return RedirectToAction("Admin", "Connection"); }
            return View(db.Person.Include(m => m.PersonRole).ToList());
        }

        //
        // GET: /Person/Details/5

        public ActionResult Details(int id = 0)
        {
            Person person = db.Person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        //
        // GET: /Person/Create
        
        public ActionResult Create()
        {
            ViewBag.PersonRoleID = new SelectList(db.PersonRole, "ID", "Role");
            return View();
        }

        //
        // POST: /Person/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Person person)
        {
            if (ModelState.IsValid)
            {
                db.Person.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonRoleID = new SelectList(db.PersonRole, "ID", "Role", person.PersonRoleID);
            return View(person);
        }

        //
        // GET: /Person/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Person person = db.Person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonRoleID = new SelectList(db.PersonRole, "ID", "Role");
            return View(person);
        }

        //
        // POST: /Person/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        //
        // GET: /Person/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Person person = db.Person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        //
        // POST: /Person/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Person.Find(id);
            db.Person.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Activity/AddFriend.cshtml
@model Project.Models.Person

@{
    ViewBag.Title = "AddFriend";
}

<h2>AddFriend</h2>

Views/Activity/Contribution.cshtml
@model IEnumerable<Project.Models.Contribution>

@{
    ViewBag.Title = "Index";
}

<h2>This is all the Contribution by guests</h2>


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GuestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContributionType.Type)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GuestName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContributionType.Type)
            </td>
           
        </tr>
    }

</table>

Views/Activity/Create.cshtml
@model Project.Models.Activity

@{
    ViewBag.Title = "Create";
}

@{
    string isadmin = Session["Admin"].ToString();
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Activity</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Time)
            @Html.ValidationMessageFor(model => model.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActivityTypeID, "ActivityType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ActivityTypeID")
            @Html.ValidationMessageFor(model => model.ActivityTypeID)
        </div>

        @if (isadmin=="Admin")
{
            <div class="editor-label">
            @Html.LabelFor(model => model.ActivityStatusID, "ActivityStatus")
            </div>
            <div class="editor-field">
            @Html.DropDownList("ActivityStatusID")
            @Html.ValidationMessageFor(model => model.ActivityStatusID)
            </div>
        }

        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Activity/Delete.cshtml
@model Project.Models.Activity

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Activity</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityType.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityType.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityStatus.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityStatus.Status)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Activity/Details.cshtml
@model Project.Models.Activity

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Activity</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityType.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityType.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityStatus.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityStatus.Status)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Activity/Edit.cshtml
@model Project.Models.Activity

@{
    ViewBag.Title = "Edit";
}
@{
    string isadmin = Session["Admin"].ToString();
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Activity</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Time)
            @Html.ValidationMessageFor(model => model.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActivityTypeID, "ActivityType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ActivityTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.ActivityTypeID)
        </div>
        @if (isadmin == "Admin")
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.ActivityStatusID, "ActivityStatus")
            </div>
            <div class="editor-field">
                @Html.DropDownList("ActivityStatusID")
                @Html.ValidationMessageFor(model => model.ActivityStatusID)
            </div>
        }

        

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Activity/Friend.cshtml
@model IEnumerable<Project.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Here is all the friend</h2>




@using (Html.BeginForm())
{
    <p>
        
        Name:@Html.TextBox("FriendName")<br />
        <input type="submit" value="Search" />
    </p>
}
@if (@Model.Count() == 0)
{
    <h4>no person has been founded</h4>
}


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nickname)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nickname)
            </td>
         
            
        </tr>
    }

</table>

@Html.ActionLink("Add Friend", "AddFriend")

Views/Activity/Index.cshtml
@model IEnumerable<Project.Models.Activity>

@{
    ViewBag.Title = "Index";
}
<div style="margin-left:370px;">
    @Html.ActionLink("Edit  your profile", "Edit", "Person", new { id = int.Parse(Session["id"].ToString()) }, null) <br>
    @Html.ActionLink("Log Out", "Logout")<br>
    @Html.ActionLink("Friend", "Friend")<br>
    @Html.ActionLink("Log as Admin", "Admin", "Connection") <br>
</div>

<h2>This is @Session["Name"]'s Activities </h2>



<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivityType.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivityStatus.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityType.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityStatus.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }) <br>
            @Html.ActionLink("View Contribution", "Contribution", new { id = item.ID })
        </td>
    </tr>
}

</table>