Models/Contribution.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public int ID { get; set; }
        public string GuestName { get; set; }
        public string Quantity { get; set; }
        public int EventId { get; set; }
        public int ContributionTypeID { get; set; }
    
        public virtual ContributionType ContributionType { get; set; }
    }
}

Models/ContributionType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionType
    {
        public ContributionType()
        {
            this.Contribution = new HashSet<Contribution>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Contribution> Contribution { get; set; }
    }
}

Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ActivityController : Controller
    {
        private MainDBContext db = new MainDBContext();

        //
        // GET: /Activity/

        public ActionResult Index()
        {


            if (Session["ID"]==null) { return RedirectToAction("Index", "Connection"); }
            else
            {
                if (Session["Admin"].ToString() != "Admin")
                {
                    int personid = int.Parse(Session["ID"].ToString());
                    var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus).Where(a => a.PersonID == personid);
                    ViewBag.name = Session["Name"];
                    return View(activity.ToList());
                }
                else {
                    var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus);

                    return View(activity.ToList());
                }
                
            }
        }

        //
        // GET: /Activity/Details/5

        public ActionResult Details(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // GET: /Activity/Create

        public ActionResult Create()
        {
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type");
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status");
            return View();
        }
        
        //
        // POST: /Activity/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Activity activity)
        {
            if (ModelState.IsValid)
            {

                int personid = int.Parse(Session["ID"].ToString());
                activity.PersonID = personid;
                activity.PersonName = Session["Name"].ToString();
                activity.ActivityStatusID = 3;
                db.Activity.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // GET: /Activity/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // POST: /Activity/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Activity activity)
        {
            if (ModelState.IsValid)
            {
                int personid = int.Parse(Session["ID"].ToString());
                activity.PersonID = personid;
                activity.ActivityStatusID = 3;
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActivityTypeID = new SelectList(db.ActivityType, "ID", "Type", activity.ActivityTypeID);
            ViewBag.ActivityStatusID = new SelectList(db.ActivityStatus, "ID", "Status", activity.ActivityStatusID);
            return View(activity);
        }

        //
        // GET: /Activity/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Activity activity = db.Activity.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activity.Find(id);
            db.Activity.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Connection");
        }

        public ActionResult Friend(string FriendName)
        {

            if (!string.IsNullOrEmpty(FriendName)) { return View(db.Person.Include(m => m.PersonRole).Where(m => m.Name.Contains(FriendName)).ToList()); }
            return View(db.Person.Include(m => m.PersonRole).ToList());
        }

        public ActionResult AddFriend()
        {

            return View();
        }

        public ActionResult Contribution(int id=0)
        {
            var contributionlist = db.Contribution.Where(c => c.EventId==id);
            return View(contributionlist.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ContributionController : Controller
    {
        private MainDBContext db = new MainDBContext();

        //
        // GET: /Contribution/

        public ActionResult Index()
        {
            var activity = db.Activity.Include(a => a.ActivityType).Include(a => a.ActivityStatus);
            
            return View(activity.ToList());
        }


        
        public ActionResult Viewall()
        {

            var contribution = db.Contribution.Include(c => c.ContributionType);
            return View(contribution.ToList());
        }

        //
        // GET: /Contribution/Details/5

        public ActionResult Details(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // GET: /Contribution/Create

        public ActionResult Create(int id = 0)
        {
            Session["EventID"] = id;
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type");
            return View();
        }

        //
        // POST: /Contribution/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                contribution.EventId = int.Parse(@Session["EventID"].ToString());
                db.Contribution.Add(contribution);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // POST: /Contribution/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contribution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionType, "ID", "Type", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Contribution contribution = db.Contribution.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // POST: /Contribution/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contribution contribution = db.Contribution.Find(id);
            db.Contribution.Remove(contribution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Contribution/Create.cshtml
@model Project.Models.Contribution

@{
    ViewBag.Title = "Create";
    
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contribution</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.GuestName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GuestName)
            @Html.ValidationMessageFor(model => model.GuestName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.ContributionTypeID, "ContributionType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ContributionTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.ContributionTypeID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Contribution/Index.cshtml
@model IEnumerable<Project.Models.Activity>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("View all the Contribution", "Viewall") 

<table>
    <tr>
        <th>
            Creator
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivityType.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivityStatus.Status)
        </th>
        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActivityType.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActivityStatus.Status)
            </td>
            
            <td>
                @Html.ActionLink("Contribute to thie Event", "Create", new { id = item.ID }) |
                
            </td>
        </tr>
    }

</table>

Views/Contribution/Viewall.cshtml
@model IEnumerable<Project.Models.Contribution>



<h2>Here are all contribution</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GuestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContributionType.Type)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GuestName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContributionType.Type)
            </td>
            <td>@Html.ActionLink("Activity Details", "Details", "Activity", new { id = item.EventId }, null)
                </td>
            
            
        </tr>
    }

</table>